// Generated by CoffeeScript 1.6.2
(function() {
  ig.module('game.gui.minimap').requires('impact.background-map').defines(function() {
    return tj.Minimap = ig.BackgroundMap.extend({
      chunkSize: 256,
      preRender: true,
      enabled: false,
      foreground: true,
      generated: false,
      scaleRatio: 16,
      init: function(game) {
        var data, tileSize;

        data = game.backgroundMaps[0].data;
        tileSize = game.tileSize / this.scaleRatio;
        this.canvas_h = tileSize * data.length;
        this.canvas_w = tileSize * data[0].length;
        return this.parent(tileSize, data, 'public/media/minimap_tileset.png');
      },
      generate: function() {
        if (!this.tiles.loaded || this.generated) {
          return;
        }
        this.preRenderMapToChunks();
        this.$map = $('<div id="minimap"></div>');
        this.$map.css({
          top: ig.game.tileSize,
          right: ig.game.rOffset
        });
        this.$map.append(this.preRenderedChunks[0][0]);
        this.$dynamic = $('<canvas class="dynamic"></canvas>');
        this.$dynamic.prop('width', this.canvas_w);
        this.$dynamic.prop('height', this.canvas_h);
        this.$map.append(this.$dynamic);
        $('body').append(this.$map);
        return this.generated = true;
      },
      update: function() {
        var ctx, h, w, x, y;

        if (this.generated) {
          ctx = this.$dynamic[0].getContext('2d');
          ctx.clearRect(0, 0, this.canvas_w, this.canvas_h);
          h = ig.game.play_h / ig.game.tileSize * 2;
          w = ig.game.play_w / ig.game.tileSize * 2;
          x = Math.round(ig.game.screen.x / ig.game.tileSize * 2);
          y = Math.round(ig.game.screen.y / ig.game.tileSize * 2);
          return ctx.strokeRect(x, y, w, h);
        } else {
          return this.generate();
        }
      }
    });
  });

}).call(this);
